var dir_0028a667593e2831e4e1b60ec4f84c69 =
[
    [ "BitmapShapes", "dir_97008818a760847fc47861b7d875ec62.html", "dir_97008818a760847fc47861b7d875ec62" ],
    [ "AnalogAlphaMatrixBitmapAnimationEffect.cs", "_analog_alpha_matrix_bitmap_animation_effect_8cs.html", "_analog_alpha_matrix_bitmap_animation_effect_8cs" ],
    [ "AnalogAlphaMatrixBitmapEffect.cs", "_analog_alpha_matrix_bitmap_effect_8cs.html", "_analog_alpha_matrix_bitmap_effect_8cs" ],
    [ "AnalogAlphaMatrixFlickerEffect.cs", "_analog_alpha_matrix_flicker_effect_8cs.html", "_analog_alpha_matrix_flicker_effect_8cs" ],
    [ "AnalogAlphaMatrixShiftEffect.cs", "_analog_alpha_matrix_shift_effect_8cs.html", "_analog_alpha_matrix_shift_effect_8cs" ],
    [ "AnalogAlphaMatrixValueEffect.cs", "_analog_alpha_matrix_value_effect_8cs.html", "_analog_alpha_matrix_value_effect_8cs" ],
    [ "AnimationBehaviourEnum.cs", "_animation_behaviour_enum_8cs.html", "_animation_behaviour_enum_8cs" ],
    [ "IMatrixBitmapEffect.cs", "_i_matrix_bitmap_effect_8cs.html", "_i_matrix_bitmap_effect_8cs" ],
    [ "IMatrixEffect.cs", "_i_matrix_effect_8cs.html", "_i_matrix_effect_8cs" ],
    [ "MatrixAnimationStepDirectionEnum.cs", "_matrix_animation_step_direction_enum_8cs.html", "_matrix_animation_step_direction_enum_8cs" ],
    [ "MatrixBitmapAnimationEffectBase.cs", "_matrix_bitmap_animation_effect_base_8cs.html", "_matrix_bitmap_animation_effect_base_8cs" ],
    [ "MatrixBitmapEffectBase.cs", "_matrix_bitmap_effect_base_8cs.html", "_matrix_bitmap_effect_base_8cs" ],
    [ "MatrixEffectBase.cs", "_matrix_effect_base_8cs.html", "_matrix_effect_base_8cs" ],
    [ "MatrixFlickerEffectBase.cs", "_matrix_flicker_effect_base_8cs.html", "_matrix_flicker_effect_base_8cs" ],
    [ "MatrixFX.cs", "_matrix_f_x_8cs.html", null ],
    [ "MatrixPlasmaEffectBase.cs", "_matrix_plasma_effect_base_8cs.html", "_matrix_plasma_effect_base_8cs" ],
    [ "MatrixShiftDirectionEnum.cs", "_matrix_shift_direction_enum_8cs.html", "_matrix_shift_direction_enum_8cs" ],
    [ "MatrixShiftEffectBase.cs", "_matrix_shift_effect_base_8cs.html", "_matrix_shift_effect_base_8cs" ],
    [ "MatrixValueEffectBase.cs", "_matrix_value_effect_base_8cs.html", "_matrix_value_effect_base_8cs" ],
    [ "RGBAMatrixBitmapAnimationEffect.cs", "_r_g_b_a_matrix_bitmap_animation_effect_8cs.html", "_r_g_b_a_matrix_bitmap_animation_effect_8cs" ],
    [ "RGBAMatrixBitmapEffect.cs", "_r_g_b_a_matrix_bitmap_effect_8cs.html", "_r_g_b_a_matrix_bitmap_effect_8cs" ],
    [ "RGBAMatrixColorEffect.cs", "_r_g_b_a_matrix_color_effect_8cs.html", "_r_g_b_a_matrix_color_effect_8cs" ],
    [ "RGBAMatrixColorScaleBitmapAnimationEffect.cs", "_r_g_b_a_matrix_color_scale_bitmap_animation_effect_8cs.html", "_r_g_b_a_matrix_color_scale_bitmap_animation_effect_8cs" ],
    [ "RGBAMatrixColorScaleBitmapEffect.cs", "_r_g_b_a_matrix_color_scale_bitmap_effect_8cs.html", "_r_g_b_a_matrix_color_scale_bitmap_effect_8cs" ],
    [ "RGBAMatrixColorScaleShapeEffect.cs", "_r_g_b_a_matrix_color_scale_shape_effect_8cs.html", "_r_g_b_a_matrix_color_scale_shape_effect_8cs" ],
    [ "RGBAMatrixFlickerEffect.cs", "_r_g_b_a_matrix_flicker_effect_8cs.html", "_r_g_b_a_matrix_flicker_effect_8cs" ],
    [ "RGBAMatrixPlasmaEffect.cs", "_r_g_b_a_matrix_plasma_effect_8cs.html", "_r_g_b_a_matrix_plasma_effect_8cs" ],
    [ "RGBAMatrixShapeEffect.cs", "_r_g_b_a_matrix_shape_effect_8cs.html", "_r_g_b_a_matrix_shape_effect_8cs" ],
    [ "RGBAMatrixShiftEffect.cs", "_r_g_b_a_matrix_shift_effect_8cs.html", "_r_g_b_a_matrix_shift_effect_8cs" ]
];