var searchData=
[
  ['cabinet_0',['Cabinet',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_250___architecture.html#architecture_cabinet',1,'']]],
  ['cabinet_20config_20tab_1',['Cabinet Config tab',['../globalconfig2.html#globalconfig_cabinetconfig',1,'']]],
  ['cabinet_20configs_2',['User Cabinet configs',['../configexamples.html#configexamples_users',1,'']]],
  ['cabinet_20configuration_3',['Cabinet Configuration',['../cabinetconfig.html',1,'Cabinet Configuration'],['../installation.html#installation_cabinetconfig',1,'Cabinet Configuration']]],
  ['cabinet_20configuration_4',['Example cabinet configuration',['../cabinetconfig.html#cabinetconfig_example',1,'']]],
  ['cabinet_20configuration_20examples_5',['Cabinet Configuration examples',['../configexamples.html',1,'']]],
  ['cabinet_20configuration_20file_6',['Cabinet configuration file',['../cabinetconfig.html#cabinetconfig_configfile',1,'']]],
  ['cabinets_7',['Welcome to the DirectOutput framework R3 for virtual pinball cabinets',['../index.html#autotoc_md11',1,'']]],
  ['chaining_20of_20effect_20effects_8',['Stacking/chaining of effect effects',['../fx.html#fx_stacking',1,'']]],
  ['changing_20the_20source_20code_20guidelines_9',['Extending and changing the source code (guidelines)',['../sourcecode.html#sourcecode_extend',1,'']]],
  ['check_20b2s_20server_20path_10',['Check B2S.Server Path',['../troubleshooting.html#troubleshooting_b2sserver',1,'']]],
  ['code_11',['Code',['../sourcecode.html',1,'Source Code'],['../downloads.html#downloads_sourcecode',1,'Source Code']]],
  ['code_12',['code',['../contribute.html#contribute_source',1,'Contribute to the source code'],['../sourcecode.html#sourcecode_fork',1,'Download source code/Fork source code'],['../sourcecode.html#sourcecode_use',1,'Using the source code']]],
  ['code_20fork_20source_20code_13',['Download source code/Fork source code',['../sourcecode.html#sourcecode_fork',1,'']]],
  ['code_20guidelines_14',['Extending and changing the source code (guidelines)',['../sourcecode.html#sourcecode_extend',1,'']]],
  ['code_20pull_20requests_15',['Contribute your code/Pull requests',['../sourcecode.html#sourcecode_pull',1,'']]],
  ['colororder_16',['ColorOrder',['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_LedStrip_ColorOrder',1,'']]],
  ['colors_20section_17',['Colors Section',['../inifiles.html#inifiles_settingscolors',1,'']]],
  ['commands_18',['Score commands',['../tableconfig.html#tableconfig_VPEMscore',1,'']]],
  ['comport_19',['ComPort',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_ComPort_PinControl_ComPort',1,'ComPort'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_PinOne_PinOne_ComPort',1,'ComPort']]],
  ['comportbaudrate_20',['ComPortBaudRate',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortBaudRate',1,'ComPortBaudRate'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortBaudRate',1,'ComPortBaudRate']]],
  ['comportdatabits_21',['ComPortDataBits',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortDataBits',1,'ComPortDataBits'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortDataBits',1,'ComPortDataBits']]],
  ['comportdtrenable_22',['ComPortDtrEnable',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortDtrEnable',1,'ComPortDtrEnable'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortDtrEnable',1,'ComPortDtrEnable']]],
  ['comporthandshakeendwaitms_23',['ComPortHandshakeEndWaitMs',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortHandshakeEndWaitMs',1,'ComPortHandshakeEndWaitMs'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortHandshakeEndWaitMs',1,'ComPortHandshakeEndWaitMs']]],
  ['comporthandshakestartwaitms_24',['ComPortHandshakeStartWaitMs',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortHandshakeStartWaitMs',1,'ComPortHandshakeStartWaitMs'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortHandshakeStartWaitMs',1,'ComPortHandshakeStartWaitMs']]],
  ['comportname_25',['ComPortName',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortName',1,'ComPortName'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortName',1,'ComPortName']]],
  ['comportopenwaitms_26',['ComPortOpenWaitMs',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortOpenWaitMs',1,'ComPortOpenWaitMs'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortOpenWaitMs',1,'ComPortOpenWaitMs']]],
  ['comportparity_27',['ComPortParity',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortParity',1,'ComPortParity'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortParity',1,'ComPortParity']]],
  ['comportstopbits_28',['ComPortStopBits',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortStopBits',1,'ComPortStopBits'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortStopBits',1,'ComPortStopBits']]],
  ['comporttimeoutms_29',['ComPortTimeOutMs',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_TeensyStripController_ComPortTimeOutMs',1,'ComPortTimeOutMs'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WemosD1MPStripController_ComPortTimeOutMs',1,'ComPortTimeOutMs']]],
  ['condition_30',['Condition',['../fx_builtin.html#DirectOutput_FX_ConditionFX_TableElementConditionEffect_Condition',1,'']]],
  ['config_31',['config',['../configexamples.html#configexamples_arngrim',1,'Arngrims config'],['../configexamples.html#configexamples_swisslizard',1,'Swisslizards config']]],
  ['config_20dof_20section_32',['Config DOF Section',['../inifiles.html#inifiles_settingsconfigouts',1,'']]],
  ['config_20editor_33',['Global config editor',['../globalconfig2.html#globalconfig_editor',1,'']]],
  ['config_20examples_20templates_34',['Config Examples/Templates',['../configexamples.html#configexamples_examples',1,'']]],
  ['config_20file_35',['Table config file',['../tableconfigfile.html#tableconfigfile_configfilestructure',1,'']]],
  ['config_20files_36',['Table config files',['../downloads.html#downloads_config',1,'']]],
  ['config_20tab_37',['Cabinet Config tab',['../globalconfig2.html#globalconfig_cabinetconfig',1,'']]],
  ['config_20tool_38',['Table configuration and config tool',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_290___credits.html#autotoc_md6',1,'']]],
  ['configs_39',['User Cabinet configs',['../configexamples.html#configexamples_users',1,'']]],
  ['configuration_40',['Configuration',['../installation.html#installation_b2sserverconfig',1,'B2S.Server Configuration'],['../cabinetconfig.html',1,'Cabinet Configuration'],['../installation.html#installation_cabinetconfig',1,'Cabinet Configuration'],['../installation.html#installation_configuration',1,'Configuration'],['../D:/a/DirectOutput/DirectOutput/ProPinballSlave/README.md#autotoc_md15',1,'Configuration'],['../globalconfig2.html',1,'Global Configuration'],['../installation.html#installation_globalconfig',1,'Global Configuration'],['../installation.html',1,'Installation and Configuration'],['../installation.html#installation_tableconfig',1,'Table Configuration']]],
  ['configuration_41',['configuration',['../cabinetconfig.html#cabinetconfig_example',1,'Example cabinet configuration'],['../installation.html#installation_autoconfiguration',1,'Using Auto configuration'],['../tableconfig.html',1,'VP Table configuration']]],
  ['configuration_20and_20config_20tool_42',['Table configuration and config tool',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_290___credits.html#autotoc_md6',1,'']]],
  ['configuration_20examples_43',['Cabinet Configuration examples',['../configexamples.html',1,'']]],
  ['configuration_20file_44',['configuration file',['../cabinetconfig.html#cabinetconfig_configfile',1,'Cabinet configuration file'],['../tableconfigfile.html',1,'Table configuration file']]],
  ['configuration_20files_45',['Using configuration files',['../installation.html#installation_configfiles',1,'']]],
  ['configure_20ss_20tables_46',['Configure SS tables',['../tableconfig.html#tableconfig_VPSSconfig',1,'']]],
  ['contribute_47',['Contribute',['../contribute.html',1,'']]],
  ['contribute_20the_20to_20documentation_48',['Contribute the to documentation',['../contribute.html#contribute_docu',1,'']]],
  ['contribute_20to_20the_20source_20code_49',['Contribute to the source code',['../contribute.html#contribute_source',1,'']]],
  ['contribute_20your_20code_20pull_20requests_50',['Contribute your code/Pull requests',['../sourcecode.html#sourcecode_pull',1,'']]],
  ['controller_51',['Teensy Strip Controller',['../hardware.html#hardware_TeensyStripController',1,'']]],
  ['controller_52',['WS2811 addressable LedStrip controller',['../hardware.html#hardware_WS2811',1,'']]],
  ['controllernumber_53',['ControllerNumber',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_DirectStripController_ControllerNumber',1,'ControllerNumber'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_AdressableLedStrip_WS2811StripController_ControllerNumber',1,'ControllerNumber']]],
  ['controllers_54',['controllers',['../contribute.html#autotoc_md3',1,'Add more output controllers'],['../outputcontrollers_builtin.html',1,'Built in Output controllers'],['../outputcontrollers.html#outputcontrollers_builtincontrollers',1,'Builtin output controllers'],['../outputcontrollers.html#outputcontrollers_implementationguideline',1,'Implementation guidelines for custom output controllers'],['../outputcontrollers.html#outputcontrollers_interfaces',1,'Interfaces for output controllers'],['../outputcontrollers.html',1,'Output controllers']]],
  ['controllers_20e_20g_20sainsmart_55',['FT245RL based controllers (e.g. SainSmart)',['../hardware.html#hardware_FT245bitbang',1,'']]],
  ['copyright_56',['About and Copyright',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_299___mainpage_and_about.html',1,'']]],
  ['core_20vbs_20adjustment_57',['Visual Pinball core.vbs Adjustment',['../installation.html#installation_visualpinballcorevbs',1,'']]],
  ['create_20more_20effects_58',['Create more effects',['../contribute.html#autotoc_md1',1,'']]],
  ['creation_59',['WiX setup (optional - required only for .msi creation)',['../md__d_1_2a_2_direct_output_2_direct_output_2_r_e_a_d_m_e___build_setup.html#autotoc_md22',1,'']]],
  ['credits_60',['Credits',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_290___credits.html',1,'']]],
  ['csscript_61',['CSScript',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_290___credits.html#autotoc_md10',1,'']]],
  ['curve_20example_62',['Fade curve example',['../configexamples.html#configexamples_teensystripcontrollerfadecurve',1,'']]],
  ['custom_20effects_63',['Custom effects',['../fx.html#fx_customeffects',1,'']]],
  ['custom_20output_20controllers_64',['Implementation guidelines for custom output controllers',['../outputcontrollers.html#outputcontrollers_implementationguideline',1,'']]],
  ['custom_20toys_65',['Implementation guidelines for custom toys',['../toys.html#toys_implementationguideline',1,'']]]
];
