var searchData=
[
  ['id_0',['Id',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_FTDIChip_FT245RBitbangController_Id',1,'Id'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_Pac_PacLed64_Id',1,'Id'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_Pac_PacUIO_Id',1,'Id'],['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_Pac_PhilipsHueController_Id',1,'Id']]],
  ['impactfactor_1',['ImpactFactor',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_SSFImpactController_SSFImpactController_ImpactFactor',1,'']]],
  ['implementation_20guidelines_20for_20custom_20output_20controllers_2',['Implementation guidelines for custom output controllers',['../outputcontrollers.html#outputcontrollers_implementationguideline',1,'']]],
  ['implementation_20guidelines_20for_20custom_20toys_3',['Implementation guidelines for custom toys',['../toys.html#toys_implementationguideline',1,'']]],
  ['implementation_20guidelines_20for_20effects_4',['Implementation guidelines for effects',['../fx.html#fx_implementationguideline',1,'']]],
  ['important_5',['Important!',['../contribute.html#autotoc_md0',1,'']]],
  ['in_20directoutputconfig_20ledcontrol_20ini_20files_6',['Settings in DirectOutputConfig/LedControl ini files',['../inifiles.html#inifiles_settings',1,'']]],
  ['in_20effects_7',['Built in Effects',['../fx_builtin.html',1,'']]],
  ['in_20effects_8',['Built in effects',['../fx.html#fx_builtinfx',1,'']]],
  ['in_20output_20controllers_9',['Built in Output controllers',['../outputcontrollers_builtin.html',1,'']]],
  ['in_20own_20directory_20recommended_10',['Installation in own directory (Recommended)',['../installation.html#installation_installation_owndir',1,'']]],
  ['in_20toys_11',['Built in Toys',['../toy_builtin.html',1,'']]],
  ['inactivecolor_12',['InactiveColor',['../fx_builtin.html#DirectOutput_FX_RGBAFX_RGBAColorEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleShapeEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixFlickerEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixPlasmaEffect_InactiveColor',1,'InactiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixShiftEffect_InactiveColor',1,'InactiveColor']]],
  ['inactivevalue_13',['InactiveValue',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixFlickerEffect_InactiveValue',1,'InactiveValue'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixShiftEffect_InactiveValue',1,'InactiveValue'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixValueEffect_InactiveValue',1,'InactiveValue'],['../fx_builtin.html#DirectOutput_FX_AnalogToyFX_AnalogToyValueEffect_InactiveValue',1,'InactiveValue']]],
  ['ini_20file_20parameters_14',['Ini File Parameters',['../pbx.html#pbx_infilepara',1,'']]],
  ['ini_20files_15',['ini files',['../inifiles.html',1,'ini files'],['../inifiles.html#inifiles_settings',1,'Settings in DirectOutputConfig/LedControl ini files'],['../installation.html#installation_ledcontrolini',1,'Using directoutputconfig.ini files']]],
  ['ini_20files_20tab_16',['Ini Files tab',['../globalconfig2.html#globalconfig_inifiles',1,'']]],
  ['initialization_17',['Initialization',['../tableconfig.html#tableconfig_VPEMinit',1,'']]],
  ['installation_18',['Installation',['../installation.html#installation_installation',1,'Installation'],['../D:/a/DirectOutput/DirectOutput/ProPinballSlave/README.md#autotoc_md14',1,'Installation']]],
  ['installation_20and_20configuration_19',['Installation and Configuration',['../installation.html',1,'']]],
  ['installation_20in_20own_20directory_20recommended_20',['Installation in own directory (Recommended)',['../installation.html#installation_installation_owndir',1,'']]],
  ['installation_20within_20hosting_20application_20directory_20structure_21',['Installation within hosting application directory structure',['../installation.html#installation_installation_hostappdir',1,'']]],
  ['instrumentation_22',['file instrumentation',['../globalconfig2.html#Log',1,'']]],
  ['interface_23',['interface',['../outputcontrollers.html#outputcontrollers_ioutput',1,'IOutput interface'],['../outputcontrollers.html#outputcontrollers_ioutputcontroller',1,'IOutputController interface']]],
  ['interfaces_20for_20output_20controllers_24',['Interfaces for output controllers',['../outputcontrollers.html#outputcontrollers_interfaces',1,'']]],
  ['introduction_25',['Introduction',['../tableconfig.html#tableconfig_intro',1,'Introduction'],['../pbx.html#pbx_intro',1,'Introduction'],['../hardware.html#hardware_intro',1,'Introduction'],['../globalconfig2.html#globalconfig_introduction',1,'Introduction'],['../cabinetconfig.html#cabinetconfig_introduction',1,'Introduction'],['../tableconfigfile.html#tableconfigfile_introduction',1,'Introduction'],['../configexamples.html#configexamples_introduction',1,'Introduction'],['../inifiles.html#inifiles_introduction',1,'Introduction'],['../fx.html#fx_introduction',1,'Introduction'],['../toys.html#toys_introduction',1,'Introduction'],['../outputcontrollers.html#outputcontrollers_introduction',1,'Introduction'],['../sourcecode.html#sourcecode_introduction',1,'Introduction']]],
  ['ioutput_20interface_26',['IOutput interface',['../outputcontrollers.html#outputcontrollers_ioutput',1,'']]],
  ['ioutputcontroller_20interface_27',['IOutputController interface',['../outputcontrollers.html#outputcontrollers_ioutputcontroller',1,'']]],
  ['is_20where_28',['What is where',['../sourcecode.html#sourcecode_where',1,'']]],
  ['issues_29',['Report bugs and issues',['../contribute.html#contribute_bugs',1,'']]],
  ['it_20works_30',['How it works',['../inifiles.html#inifiles_howitworks',1,'']]]
];
