var searchData=
[
  ['about_20and_20copyright_0',['About and Copyright',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_299___mainpage_and_about.html',1,'']]],
  ['activecolor_1',['ActiveColor',['../fx_builtin.html#DirectOutput_FX_RGBAFX_RGBAColorEffect_ActiveColor',1,'ActiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorEffect_ActiveColor',1,'ActiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_ActiveColor',1,'ActiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapEffect_ActiveColor',1,'ActiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleShapeEffect_ActiveColor',1,'ActiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixFlickerEffect_ActiveColor',1,'ActiveColor'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixShiftEffect_ActiveColor',1,'ActiveColor']]],
  ['activecolor1_2',['ActiveColor1',['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixPlasmaEffect_ActiveColor1',1,'']]],
  ['activecolor2_3',['ActiveColor2',['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixPlasmaEffect_ActiveColor2',1,'']]],
  ['activevalue_4',['ActiveValue',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixFlickerEffect_ActiveValue',1,'ActiveValue'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixShiftEffect_ActiveValue',1,'ActiveValue'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixValueEffect_ActiveValue',1,'ActiveValue'],['../fx_builtin.html#DirectOutput_FX_AnalogToyFX_AnalogToyValueEffect_ActiveValue',1,'ActiveValue']]],
  ['add_20more_20and_20better_20toys_5',['Add more and better toys',['../contribute.html#autotoc_md2',1,'']]],
  ['add_20more_20output_20controllers_6',['Add more output controllers',['../contribute.html#autotoc_md3',1,'']]],
  ['addressable_20ledstrip_20controller_7',['WS2811 addressable LedStrip controller',['../hardware.html#hardware_WS2811',1,'']]],
  ['adjustment_8',['Visual Pinball core.vbs Adjustment',['../installation.html#installation_visualpinballcorevbs',1,'']]],
  ['analogalphamatrixbitmapanimationeffect_9',['AnalogAlphaMatrixBitmapAnimationEffect',['../fx_builtin.html#use_DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect',1,'']]],
  ['analogalphamatrixbitmapeffect_10',['AnalogAlphaMatrixBitmapEffect',['../fx_builtin.html#use_DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapEffect',1,'']]],
  ['analogalphamatrixflickereffect_11',['AnalogAlphaMatrixFlickerEffect',['../fx_builtin.html#use_DirectOutput_FX_MatrixFX_AnalogAlphaMatrixFlickerEffect',1,'']]],
  ['analogalphamatrixshifteffect_12',['AnalogAlphaMatrixShiftEffect',['../fx_builtin.html#use_DirectOutput_FX_MatrixFX_AnalogAlphaMatrixShiftEffect',1,'']]],
  ['analogalphamatrixvalueeffect_13',['AnalogAlphaMatrixValueEffect',['../fx_builtin.html#use_DirectOutput_FX_MatrixFX_AnalogAlphaMatrixValueEffect',1,'']]],
  ['analogalphatoy_14',['AnalogAlphaToy',['../toy_builtin.html#use_DirectOutput_Cab_Toys_Layer_AnalogAlphaToy',1,'']]],
  ['analogalphatoygroup_15',['AnalogAlphaToyGroup',['../toy_builtin.html#use_DirectOutput_Cab_Toys_Virtual_AnalogAlphaToyGroup',1,'']]],
  ['analogtoyvalueeffect_16',['AnalogToyValueEffect',['../fx_builtin.html#use_DirectOutput_FX_AnalogToyFX_AnalogToyValueEffect',1,'']]],
  ['and_20better_20toys_17',['Add more and better toys',['../contribute.html#autotoc_md2',1,'']]],
  ['and_20changing_20the_20source_20code_20guidelines_18',['Extending and changing the source code (guidelines)',['../sourcecode.html#sourcecode_extend',1,'']]],
  ['and_20config_20tool_19',['Table configuration and config tool',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_290___credits.html#autotoc_md6',1,'']]],
  ['and_20configuration_20',['Installation and Configuration',['../installation.html',1,'']]],
  ['and_20copyright_21',['About and Copyright',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_299___mainpage_and_about.html',1,'']]],
  ['and_20issues_22',['Report bugs and issues',['../contribute.html#contribute_bugs',1,'']]],
  ['and_20original_20tables_23',['VP electro mechanical (EM) tables and original tables',['../tableconfig.html#tableconfig_VPEM',1,'']]],
  ['and_20support_24',['Testing and support',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_290___credits.html#autotoc_md5',1,'']]],
  ['animation_20paras_25',['Bitmap Animation Paras',['../inifiles.html#inifiles_bitmapanimationpara',1,'']]],
  ['animationbehaviour_26',['AnimationBehaviour',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect_AnimationBehaviour',1,'AnimationBehaviour'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapAnimationEffect_AnimationBehaviour',1,'AnimationBehaviour'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_AnimationBehaviour',1,'AnimationBehaviour']]],
  ['animationframecount_27',['AnimationFrameCount',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect_AnimationFrameCount',1,'AnimationFrameCount'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapAnimationEffect_AnimationFrameCount',1,'AnimationFrameCount'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_AnimationFrameCount',1,'AnimationFrameCount']]],
  ['animationframedurationms_28',['AnimationFrameDurationMs',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect_AnimationFrameDurationMs',1,'AnimationFrameDurationMs'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapAnimationEffect_AnimationFrameDurationMs',1,'AnimationFrameDurationMs'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_AnimationFrameDurationMs',1,'AnimationFrameDurationMs']]],
  ['animationstepdirection_29',['AnimationStepDirection',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect_AnimationStepDirection',1,'AnimationStepDirection'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapAnimationEffect_AnimationStepDirection',1,'AnimationStepDirection'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_AnimationStepDirection',1,'AnimationStepDirection']]],
  ['animationstepsize_30',['AnimationStepSize',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect_AnimationStepSize',1,'AnimationStepSize'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapAnimationEffect_AnimationStepSize',1,'AnimationStepSize'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_AnimationStepSize',1,'AnimationStepSize']]],
  ['application_31',['LedControl File Testing Application',['../inifiles.html#inifiles_testingapp',1,'']]],
  ['application_20directory_20structure_32',['Installation within hosting application directory structure',['../installation.html#installation_installation_hostappdir',1,'']]],
  ['architecture_33',['Architecture',['../md__d_1_2a_2_direct_output_2_direct_output_2_documentation_250___architecture.html',1,'']]],
  ['area_20effect_20parameters_34',['Matrix/area effect parameters',['../inifiles.html#inifiles_matrix',1,'']]],
  ['arngrims_20config_35',['Arngrims config',['../configexamples.html#configexamples_arngrim',1,'']]],
  ['art_20net_20dmx_36',['Art-Net / DMX',['../hardware.html#hardware_artnet',1,'']]],
  ['artnet_37',['ArtNet',['../outputcontrollers_builtin.html#use_DirectOutput_Cab_Out_DMX_ArtNet',1,'']]],
  ['assigned_20static_20effects_20section_38',['Assigned static effects section',['../tableconfigfile.html#tableconfigfile_configfilestructurestaticeffects',1,'']]],
  ['assignedeffects_39',['AssignedEffects',['../fx_builtin.html#DirectOutput_FX_ListFX_ListEffect_AssignedEffects',1,'']]],
  ['auto_20configuration_40',['Using Auto configuration',['../installation.html#installation_autoconfiguration',1,'']]]
];
