var searchData=
[
  ['fade_20curve_20example_0',['Fade curve example',['../configexamples.html#configexamples_teensystripcontrollerfadecurve',1,'']]],
  ['fadedownduration_1',['FadeDownDuration',['../fx_builtin.html#DirectOutput_FX_TimmedFX_FadeEffect_FadeDownDuration',1,'']]],
  ['fadedurationmode_2',['FadeDurationMode',['../fx_builtin.html#DirectOutput_FX_TimmedFX_FadeEffect_FadeDurationMode',1,'']]],
  ['fadeeffect_3',['FadeEffect',['../fx_builtin.html#use_DirectOutput_FX_TimmedFX_FadeEffect',1,'']]],
  ['fademode_4',['FadeMode',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapAnimationEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixBitmapEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixFlickerEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixShiftEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixValueEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_AnalogToyFX_AnalogToyValueEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_RGBAFX_RGBAColorEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapAnimationEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixBitmapEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapAnimationEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleBitmapEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixColorScaleShapeEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixFlickerEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixPlasmaEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixShapeEffect_FadeMode',1,'FadeMode'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixShiftEffect_FadeMode',1,'FadeMode']]],
  ['fadeupduration_5',['FadeUpDuration',['../fx_builtin.html#DirectOutput_FX_TimmedFX_FadeEffect_FadeUpDuration',1,'']]],
  ['fadingcurvename_6',['FadingCurveName',['../toy_builtin.html#DirectOutput_Cab_Toys_Layer_AnalogAlphaToy_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_GearMotor_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_Lamp_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_LedStrip_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_Motor_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Layer_RGBAToy_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_RGBLed_FadingCurveName',1,'FadingCurveName'],['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_Shaker_FadingCurveName',1,'FadingCurveName']]],
  ['file_7',['file',['../cabinetconfig.html#cabinetconfig_configfile',1,'Cabinet configuration file'],['../tableconfigfile.html#tableconfigfile_configfilestructure',1,'Table config file'],['../tableconfigfile.html',1,'Table configuration file']]],
  ['file_20format_8',['File format',['../globalconfig2.html#globalconfig_fileformat',1,'']]],
  ['file_20instrumentation_9',['file instrumentation',['../globalconfig2.html#Log',1,'']]],
  ['file_20locations_10',['File locations',['../inifiles.html#inifiles_directories',1,'']]],
  ['file_20numbering_11',['LedControl file numbering',['../inifiles.html#inifiles_filenumbering',1,'']]],
  ['file_20parameters_12',['Ini File Parameters',['../pbx.html#pbx_infilepara',1,'']]],
  ['file_20testing_20application_13',['LedControl File Testing Application',['../inifiles.html#inifiles_testingapp',1,'']]],
  ['files_14',['files',['../inifiles.html',1,'ini files'],['../inifiles.html#inifiles_settings',1,'Settings in DirectOutputConfig/LedControl ini files'],['../downloads.html#downloads_config',1,'Table config files'],['../installation.html#installation_configfiles',1,'Using configuration files'],['../installation.html#installation_ledcontrolini',1,'Using directoutputconfig.ini files']]],
  ['files_20tab_15',['Ini Files tab',['../globalconfig2.html#globalconfig_inifiles',1,'']]],
  ['firstlednumber_16',['FirstLedNumber',['../toy_builtin.html#DirectOutput_Cab_Toys_Hardware_LedStrip_FirstLedNumber',1,'']]],
  ['flashers_17',['Flashers',['../D:/a/DirectOutput/DirectOutput/ProPinballSlave/README.md#autotoc_md16',1,'']]],
  ['flicker_20effect_20paras_18',['Flicker Effect Paras',['../inifiles.html#inifiles_flickereffectpara',1,'']]],
  ['flickerfadedowndurationms_19',['FlickerFadeDownDurationMs',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixFlickerEffect_FlickerFadeDownDurationMs',1,'FlickerFadeDownDurationMs'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixFlickerEffect_FlickerFadeDownDurationMs',1,'FlickerFadeDownDurationMs']]],
  ['flickerfadeupdurationms_20',['FlickerFadeUpDurationMs',['../fx_builtin.html#DirectOutput_FX_MatrixFX_AnalogAlphaMatrixFlickerEffect_FlickerFadeUpDurationMs',1,'FlickerFadeUpDurationMs'],['../fx_builtin.html#DirectOutput_FX_MatrixFX_RGBAMatrixFlickerEffect_FlickerFadeUpDurationMs',1,'FlickerFadeUpDurationMs']]],
  ['flipperlevel_21',['FlipperLevel',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_SSFImpactController_SSFImpactController_FlipperLevel',1,'']]],
  ['flippers_22',['Flippers',['../D:/a/DirectOutput/DirectOutput/ProPinballSlave/README.md#autotoc_md18',1,'']]],
  ['for_20custom_20output_20controllers_23',['Implementation guidelines for custom output controllers',['../outputcontrollers.html#outputcontrollers_implementationguideline',1,'']]],
  ['for_20custom_20toys_24',['Implementation guidelines for custom toys',['../toys.html#toys_implementationguideline',1,'']]],
  ['for_20effects_25',['Implementation guidelines for effects',['../fx.html#fx_implementationguideline',1,'']]],
  ['for_20msi_20creation_26',['WiX setup (optional - required only for .msi creation)',['../md__d_1_2a_2_direct_output_2_direct_output_2_r_e_a_d_m_e___build_setup.html#autotoc_md22',1,'']]],
  ['for_20output_20controllers_27',['Interfaces for output controllers',['../outputcontrollers.html#outputcontrollers_interfaces',1,'']]],
  ['for_20pro_20pinball_28',['Bridge Library for Pro Pinball',['../D:/a/DirectOutput/DirectOutput/ProPinballBridge/README.md#autotoc_md12',1,'']]],
  ['for_20virtual_20pinball_20cabinets_29',['Welcome to the DirectOutput framework R3 for virtual pinball cabinets',['../index.html#autotoc_md11',1,'']]],
  ['fork_20source_20code_30',['Download source code/Fork source code',['../sourcecode.html#sourcecode_fork',1,'']]],
  ['format_31',['File format',['../globalconfig2.html#globalconfig_fileformat',1,'']]],
  ['framework_20r3_20for_20virtual_20pinball_20cabinets_32',['Welcome to the DirectOutput framework R3 for virtual pinball cabinets',['../index.html#autotoc_md11',1,'']]],
  ['frontexciters_33',['FrontExciters',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_SSFImpactController_SSFImpactController_FrontExciters',1,'']]],
  ['ft245rbitbangcontroller_34',['FT245RBitbangController',['../outputcontrollers_builtin.html#use_DirectOutput_Cab_Out_FTDIChip_FT245RBitbangController',1,'']]],
  ['ft245rl_20based_20controllers_20e_20g_20sainsmart_35',['FT245RL based controllers (e.g. SainSmart)',['../hardware.html#hardware_FT245bitbang',1,'']]],
  ['fullupdatethreshold_36',['FullUpdateThreshold',['../outputcontrollers_builtin.html#DirectOutput_Cab_Out_Pac_PacLed64_FullUpdateThreshold',1,'']]],
  ['fx_37',['Effects/FX',['../fx.html',1,'']]]
];
